#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clases.Contabilidad
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TECAv8")]
	public partial class DataSIsConDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTipoTransaccion(TipoTransaccion instance);
    partial void UpdateTipoTransaccion(TipoTransaccion instance);
    partial void DeleteTipoTransaccion(TipoTransaccion instance);
    partial void InsertModeloAsiento(ModeloAsiento instance);
    partial void UpdateModeloAsiento(ModeloAsiento instance);
    partial void DeleteModeloAsiento(ModeloAsiento instance);
    #endregion
		
		public DataSIsConDataContext() : 
				base(global::clases.Properties.Settings.Default.TECAv8ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataSIsConDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSIsConDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSIsConDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSIsConDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TipoTransaccion> TipoTransaccions
		{
			get
			{
				return this.GetTable<TipoTransaccion>();
			}
		}
		
		public System.Data.Linq.Table<ModeloAsiento> ModeloAsientos
		{
			get
			{
				return this.GetTable<ModeloAsiento>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModeloAsientos_Delete")]
		public int ModeloAsientos_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTransaccion", DbType="Int")] System.Nullable<int> idTransaccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secuencial)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idTransaccion, modulo, secuencial);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModeloAsientos_Update")]
		public int ModeloAsientos_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTransaccion", DbType="Int")] System.Nullable<int> idTransaccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secuencial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string debe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string haber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(1)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaModificacion", DbType="DateTime")] System.Nullable<System.DateTime> fechaModificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idTransaccion, modulo, secuencial, descripcion, debe, haber, idUsuario, fechaModificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModeloAsientos_Insertar")]
		public int ModeloAsientos_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTransaccion", DbType="Int")] System.Nullable<int> idTransaccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string debe, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string haber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(1)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaModificacion", DbType="DateTime")] System.Nullable<System.DateTime> fechaModificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idTransaccion, modulo, descripcion, debe, haber, idUsuario, fechaModificacion);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Contabilidad.TipoTransaccion")]
	public partial class TipoTransaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTransaccion;
		
		private int _modulo;
		
		private string _TipoDocumento;
		
		private string _descripcion;
		
		private EntitySet<ModeloAsiento> _ModeloAsientos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTransaccionChanging(int value);
    partial void OnIdTransaccionChanged();
    partial void OnmoduloChanging(int value);
    partial void OnmoduloChanged();
    partial void OnTipoDocumentoChanging(string value);
    partial void OnTipoDocumentoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public TipoTransaccion()
		{
			this._ModeloAsientos = new EntitySet<ModeloAsiento>(new Action<ModeloAsiento>(this.attach_ModeloAsientos), new Action<ModeloAsiento>(this.detach_ModeloAsientos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTransaccion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdTransaccion
		{
			get
			{
				return this._IdTransaccion;
			}
			set
			{
				if ((this._IdTransaccion != value))
				{
					this.OnIdTransaccionChanging(value);
					this.SendPropertyChanging();
					this._IdTransaccion = value;
					this.SendPropertyChanged("IdTransaccion");
					this.OnIdTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modulo", DbType="Int NOT NULL")]
		public int modulo
		{
			get
			{
				return this._modulo;
			}
			set
			{
				if ((this._modulo != value))
				{
					this.OnmoduloChanging(value);
					this.SendPropertyChanging();
					this._modulo = value;
					this.SendPropertyChanged("modulo");
					this.OnmoduloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(50)")]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransaccion_ModeloAsiento", Storage="_ModeloAsientos", ThisKey="IdTransaccion", OtherKey="IdTransaccion")]
		public EntitySet<ModeloAsiento> ModeloAsientos
		{
			get
			{
				return this._ModeloAsientos;
			}
			set
			{
				this._ModeloAsientos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModeloAsientos(ModeloAsiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransaccion = this;
		}
		
		private void detach_ModeloAsientos(ModeloAsiento entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransaccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Contabilidad.ModeloAsiento")]
	public partial class ModeloAsiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpresa;
		
		private int _modulo;
		
		private int _IdTransaccion;
		
		private int _secuencia;
		
		private string _descripcion;
		
		private string _debe;
		
		private string _haber;
		
		private int _IdUsuario;
		
		private System.DateTime _FechaModificacion;
		
		private EntityRef<TipoTransaccion> _TipoTransaccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpresaChanging(int value);
    partial void OnIdEmpresaChanged();
    partial void OnmoduloChanging(int value);
    partial void OnmoduloChanged();
    partial void OnIdTransaccionChanging(int value);
    partial void OnIdTransaccionChanged();
    partial void OnsecuenciaChanging(int value);
    partial void OnsecuenciaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OndebeChanging(string value);
    partial void OndebeChanged();
    partial void OnhaberChanging(string value);
    partial void OnhaberChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public ModeloAsiento()
		{
			this._TipoTransaccion = default(EntityRef<TipoTransaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this.OnIdEmpresaChanging(value);
					this.SendPropertyChanging();
					this._IdEmpresa = value;
					this.SendPropertyChanged("IdEmpresa");
					this.OnIdEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modulo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int modulo
		{
			get
			{
				return this._modulo;
			}
			set
			{
				if ((this._modulo != value))
				{
					this.OnmoduloChanging(value);
					this.SendPropertyChanging();
					this._modulo = value;
					this.SendPropertyChanged("modulo");
					this.OnmoduloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTransaccion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdTransaccion
		{
			get
			{
				return this._IdTransaccion;
			}
			set
			{
				if ((this._IdTransaccion != value))
				{
					if (this._TipoTransaccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTransaccionChanging(value);
					this.SendPropertyChanging();
					this._IdTransaccion = value;
					this.SendPropertyChanged("IdTransaccion");
					this.OnIdTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secuencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int secuencia
		{
			get
			{
				return this._secuencia;
			}
			set
			{
				if ((this._secuencia != value))
				{
					this.OnsecuenciaChanging(value);
					this.SendPropertyChanging();
					this._secuencia = value;
					this.SendPropertyChanged("secuencia");
					this.OnsecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debe", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string debe
		{
			get
			{
				return this._debe;
			}
			set
			{
				if ((this._debe != value))
				{
					this.OndebeChanging(value);
					this.SendPropertyChanging();
					this._debe = value;
					this.SendPropertyChanged("debe");
					this.OndebeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haber", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string haber
		{
			get
			{
				return this._haber;
			}
			set
			{
				if ((this._haber != value))
				{
					this.OnhaberChanging(value);
					this.SendPropertyChanging();
					this._haber = value;
					this.SendPropertyChanged("haber");
					this.OnhaberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransaccion_ModeloAsiento", Storage="_TipoTransaccion", ThisKey="IdTransaccion", OtherKey="IdTransaccion", IsForeignKey=true)]
		public TipoTransaccion TipoTransaccion
		{
			get
			{
				return this._TipoTransaccion.Entity;
			}
			set
			{
				TipoTransaccion previousValue = this._TipoTransaccion.Entity;
				if (((previousValue != value) 
							|| (this._TipoTransaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoTransaccion.Entity = null;
						previousValue.ModeloAsientos.Remove(this);
					}
					this._TipoTransaccion.Entity = value;
					if ((value != null))
					{
						value.ModeloAsientos.Add(this);
						this._IdTransaccion = value.IdTransaccion;
					}
					else
					{
						this._IdTransaccion = default(int);
					}
					this.SendPropertyChanged("TipoTransaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
