//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace datos.Seguridad
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TECAv8Entities2 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TECAv8Entities2 usando la cadena de conexión encontrada en la sección 'TECAv8Entities2' del archivo de configuración de la aplicación.
        /// </summary>
        public TECAv8Entities2() : base("name=TECAv8Entities2", "TECAv8Entities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TECAv8Entities2.
        /// </summary>
        public TECAv8Entities2(string connectionString) : base(connectionString, "TECAv8Entities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TECAv8Entities2.
        /// </summary>
        public TECAv8Entities2(EntityConnection connection) : base(connection, "TECAv8Entities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsuarioPorEmpresa> UsuarioPorEmpresa
        {
            get
            {
                if ((_UsuarioPorEmpresa == null))
                {
                    _UsuarioPorEmpresa = base.CreateObjectSet<UsuarioPorEmpresa>("UsuarioPorEmpresa");
                }
                return _UsuarioPorEmpresa;
            }
        }
        private ObjectSet<UsuarioPorEmpresa> _UsuarioPorEmpresa;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsuarioPorEmpresa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarioPorEmpresa(UsuarioPorEmpresa usuarioPorEmpresa)
        {
            base.AddObject("UsuarioPorEmpresa", usuarioPorEmpresa);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TECAv8Model2", Name="UsuarioPorEmpresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioPorEmpresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsuarioPorEmpresa.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de la propiedad IdUsuario.</param>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        public static UsuarioPorEmpresa CreateUsuarioPorEmpresa(global::System.Int32 idUsuario, global::System.Int32 idEmpresa)
        {
            UsuarioPorEmpresa usuarioPorEmpresa = new UsuarioPorEmpresa();
            usuarioPorEmpresa.IdUsuario = idUsuario;
            usuarioPorEmpresa.IdEmpresa = idEmpresa;
            return usuarioPorEmpresa;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                if (_IdEmpresa != value)
                {
                    OnIdEmpresaChanging(value);
                    ReportPropertyChanging("IdEmpresa");
                    _IdEmpresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEmpresa");
                    OnIdEmpresaChanged();
                }
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();

        #endregion
    
    }

    #endregion
    
}
