//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ComprasModel", "FK__Proveedor__IdPer__6F7F8B4B", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(datos.Compras.Persona), "Proveedor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(datos.Compras.Proveedor), true)]

#endregion

namespace datos.Compras
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CompraEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CompraEntities usando la cadena de conexión encontrada en la sección 'CompraEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public CompraEntities() : base("name=CompraEntities", "CompraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CompraEntities.
        /// </summary>
        public CompraEntities(string connectionString) : base(connectionString, "CompraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CompraEntities.
        /// </summary>
        public CompraEntities(EntityConnection connection) : base(connection, "CompraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proveedor> Proveedor
        {
            get
            {
                if ((_Proveedor == null))
                {
                    _Proveedor = base.CreateObjectSet<Proveedor>("Proveedor");
                }
                return _Proveedor;
            }
        }
        private ObjectSet<Proveedor> _Proveedor;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Persona> Persona
        {
            get
            {
                if ((_Persona == null))
                {
                    _Persona = base.CreateObjectSet<Persona>("Persona");
                }
                return _Persona;
            }
        }
        private ObjectSet<Persona> _Persona;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ProveedorDescripcion> ProveedorDescripcion
        {
            get
            {
                if ((_ProveedorDescripcion == null))
                {
                    _ProveedorDescripcion = base.CreateObjectSet<ProveedorDescripcion>("ProveedorDescripcion");
                }
                return _ProveedorDescripcion;
            }
        }
        private ObjectSet<ProveedorDescripcion> _ProveedorDescripcion;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Proveedor. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProveedor(Proveedor proveedor)
        {
            base.AddObject("Proveedor", proveedor);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Persona. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersona(Persona persona)
        {
            base.AddObject("Persona", persona);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProveedorDescripcion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProveedorDescripcion(ProveedorDescripcion proveedorDescripcion)
        {
            base.AddObject("ProveedorDescripcion", proveedorDescripcion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ComprasModel", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Persona.
        /// </summary>
        /// <param name="idPersona">Valor inicial de la propiedad IdPersona.</param>
        /// <param name="identificacion">Valor inicial de la propiedad Identificacion.</param>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        /// <param name="idTipoPersona">Valor inicial de la propiedad IdTipoPersona.</param>
        /// <param name="nombreRazonSocial">Valor inicial de la propiedad NombreRazonSocial.</param>
        /// <param name="tipoIdentificacion">Valor inicial de la propiedad TipoIdentificacion.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        /// <param name="telefonoMovil">Valor inicial de la propiedad TelefonoMovil.</param>
        /// <param name="telefonoCasa">Valor inicial de la propiedad TelefonoCasa.</param>
        /// <param name="mail">Valor inicial de la propiedad mail.</param>
        /// <param name="idEstado">Valor inicial de la propiedad IdEstado.</param>
        public static Persona CreatePersona(global::System.Int32 idPersona, global::System.Decimal identificacion, global::System.Int32 idEmpresa, global::System.Int32 idTipoPersona, global::System.String nombreRazonSocial, global::System.Int32 tipoIdentificacion, global::System.String direccion, global::System.Decimal telefonoMovil, global::System.Decimal telefonoCasa, global::System.String mail, global::System.Int32 idEstado)
        {
            Persona persona = new Persona();
            persona.IdPersona = idPersona;
            persona.Identificacion = identificacion;
            persona.IdEmpresa = idEmpresa;
            persona.IdTipoPersona = idTipoPersona;
            persona.NombreRazonSocial = nombreRazonSocial;
            persona.TipoIdentificacion = tipoIdentificacion;
            persona.direccion = direccion;
            persona.TelefonoMovil = telefonoMovil;
            persona.TelefonoCasa = telefonoCasa;
            persona.mail = mail;
            persona.IdEstado = idEstado;
            return persona;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPersona
        {
            get
            {
                return _IdPersona;
            }
            set
            {
                if (_IdPersona != value)
                {
                    OnIdPersonaChanging(value);
                    ReportPropertyChanging("IdPersona");
                    _IdPersona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPersona");
                    OnIdPersonaChanged();
                }
            }
        }
        private global::System.Int32 _IdPersona;
        partial void OnIdPersonaChanging(global::System.Int32 value);
        partial void OnIdPersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Identificacion
        {
            get
            {
                return _Identificacion;
            }
            set
            {
                OnIdentificacionChanging(value);
                ReportPropertyChanging("Identificacion");
                _Identificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Identificacion");
                OnIdentificacionChanged();
            }
        }
        private global::System.Decimal _Identificacion;
        partial void OnIdentificacionChanging(global::System.Decimal value);
        partial void OnIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                OnIdEmpresaChanging(value);
                ReportPropertyChanging("IdEmpresa");
                _IdEmpresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEmpresa");
                OnIdEmpresaChanged();
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoPersona
        {
            get
            {
                return _IdTipoPersona;
            }
            set
            {
                OnIdTipoPersonaChanging(value);
                ReportPropertyChanging("IdTipoPersona");
                _IdTipoPersona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoPersona");
                OnIdTipoPersonaChanged();
            }
        }
        private global::System.Int32 _IdTipoPersona;
        partial void OnIdTipoPersonaChanging(global::System.Int32 value);
        partial void OnIdTipoPersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreRazonSocial
        {
            get
            {
                return _NombreRazonSocial;
            }
            set
            {
                OnNombreRazonSocialChanging(value);
                ReportPropertyChanging("NombreRazonSocial");
                _NombreRazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreRazonSocial");
                OnNombreRazonSocialChanged();
            }
        }
        private global::System.String _NombreRazonSocial;
        partial void OnNombreRazonSocialChanging(global::System.String value);
        partial void OnNombreRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaNacimiento;
        partial void OnFechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaNacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String genero
        {
            get
            {
                return _genero;
            }
            set
            {
                OngeneroChanging(value);
                ReportPropertyChanging("genero");
                _genero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("genero");
                OngeneroChanged();
            }
        }
        private global::System.String _genero;
        partial void OngeneroChanging(global::System.String value);
        partial void OngeneroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoIdentificacion
        {
            get
            {
                return _TipoIdentificacion;
            }
            set
            {
                OnTipoIdentificacionChanging(value);
                ReportPropertyChanging("TipoIdentificacion");
                _TipoIdentificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoIdentificacion");
                OnTipoIdentificacionChanged();
            }
        }
        private global::System.Int32 _TipoIdentificacion;
        partial void OnTipoIdentificacionChanging(global::System.Int32 value);
        partial void OnTipoIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TelefonoGneral
        {
            get
            {
                return _TelefonoGneral;
            }
            set
            {
                OnTelefonoGneralChanging(value);
                ReportPropertyChanging("TelefonoGneral");
                _TelefonoGneral = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TelefonoGneral");
                OnTelefonoGneralChanged();
            }
        }
        private Nullable<global::System.Decimal> _TelefonoGneral;
        partial void OnTelefonoGneralChanging(Nullable<global::System.Decimal> value);
        partial void OnTelefonoGneralChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TelefonoMovil
        {
            get
            {
                return _TelefonoMovil;
            }
            set
            {
                OnTelefonoMovilChanging(value);
                ReportPropertyChanging("TelefonoMovil");
                _TelefonoMovil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TelefonoMovil");
                OnTelefonoMovilChanged();
            }
        }
        private global::System.Decimal _TelefonoMovil;
        partial void OnTelefonoMovilChanging(global::System.Decimal value);
        partial void OnTelefonoMovilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TelefonoCasa
        {
            get
            {
                return _TelefonoCasa;
            }
            set
            {
                OnTelefonoCasaChanging(value);
                ReportPropertyChanging("TelefonoCasa");
                _TelefonoCasa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TelefonoCasa");
                OnTelefonoCasaChanged();
            }
        }
        private global::System.Decimal _TelefonoCasa;
        partial void OnTelefonoCasaChanging(global::System.Decimal value);
        partial void OnTelefonoCasaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TelefonoOtros
        {
            get
            {
                return _TelefonoOtros;
            }
            set
            {
                OnTelefonoOtrosChanging(value);
                ReportPropertyChanging("TelefonoOtros");
                _TelefonoOtros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TelefonoOtros");
                OnTelefonoOtrosChanged();
            }
        }
        private Nullable<global::System.Decimal> _TelefonoOtros;
        partial void OnTelefonoOtrosChanging(Nullable<global::System.Decimal> value);
        partial void OnTelefonoOtrosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ComprasModel", "FK__Proveedor__IdPer__6F7F8B4B", "Proveedor")]
        public EntityCollection<Proveedor> Proveedor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Proveedor>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Proveedor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Proveedor>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Proveedor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ComprasModel", Name="Proveedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proveedor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proveedor.
        /// </summary>
        /// <param name="idProveedor">Valor inicial de la propiedad IdProveedor.</param>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        /// <param name="idPersona">Valor inicial de la propiedad IdPersona.</param>
        /// <param name="idTipoArticulo">Valor inicial de la propiedad IdTipoArticulo.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        public static Proveedor CreateProveedor(global::System.Int32 idProveedor, global::System.Int32 idEmpresa, global::System.Int32 idPersona, global::System.Int32 idTipoArticulo, global::System.Int32 estado)
        {
            Proveedor proveedor = new Proveedor();
            proveedor.IdProveedor = idProveedor;
            proveedor.IdEmpresa = idEmpresa;
            proveedor.IdPersona = idPersona;
            proveedor.IdTipoArticulo = idTipoArticulo;
            proveedor.Estado = estado;
            return proveedor;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProveedor
        {
            get
            {
                return _IdProveedor;
            }
            set
            {
                if (_IdProveedor != value)
                {
                    OnIdProveedorChanging(value);
                    ReportPropertyChanging("IdProveedor");
                    _IdProveedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProveedor");
                    OnIdProveedorChanged();
                }
            }
        }
        private global::System.Int32 _IdProveedor;
        partial void OnIdProveedorChanging(global::System.Int32 value);
        partial void OnIdProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                OnIdEmpresaChanging(value);
                ReportPropertyChanging("IdEmpresa");
                _IdEmpresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEmpresa");
                OnIdEmpresaChanged();
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPersona
        {
            get
            {
                return _IdPersona;
            }
            set
            {
                OnIdPersonaChanging(value);
                ReportPropertyChanging("IdPersona");
                _IdPersona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPersona");
                OnIdPersonaChanged();
            }
        }
        private global::System.Int32 _IdPersona;
        partial void OnIdPersonaChanging(global::System.Int32 value);
        partial void OnIdPersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoArticulo
        {
            get
            {
                return _IdTipoArticulo;
            }
            set
            {
                OnIdTipoArticuloChanging(value);
                ReportPropertyChanging("IdTipoArticulo");
                _IdTipoArticulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoArticulo");
                OnIdTipoArticuloChanged();
            }
        }
        private global::System.Int32 _IdTipoArticulo;
        partial void OnIdTipoArticuloChanging(global::System.Int32 value);
        partial void OnIdTipoArticuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.Int32 _Estado;
        partial void OnEstadoChanging(global::System.Int32 value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ComprasModel", "FK__Proveedor__IdPer__6F7F8B4B", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("ComprasModel.FK__Proveedor__IdPer__6F7F8B4B", "Persona", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ComprasModel", Name="ProveedorDescripcion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProveedorDescripcion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ProveedorDescripcion.
        /// </summary>
        /// <param name="idProveedor">Valor inicial de la propiedad IdProveedor.</param>
        /// <param name="idPersona">Valor inicial de la propiedad IdPersona.</param>
        /// <param name="nombreRazonSocial">Valor inicial de la propiedad NombreRazonSocial.</param>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        /// <param name="idTipoArticulo">Valor inicial de la propiedad IdTipoArticulo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        public static ProveedorDescripcion CreateProveedorDescripcion(global::System.Int32 idProveedor, global::System.Int32 idPersona, global::System.String nombreRazonSocial, global::System.Int32 idEmpresa, global::System.Int32 idTipoArticulo, global::System.String descripcion, global::System.Int32 estado)
        {
            ProveedorDescripcion proveedorDescripcion = new ProveedorDescripcion();
            proveedorDescripcion.IdProveedor = idProveedor;
            proveedorDescripcion.IdPersona = idPersona;
            proveedorDescripcion.NombreRazonSocial = nombreRazonSocial;
            proveedorDescripcion.IdEmpresa = idEmpresa;
            proveedorDescripcion.IdTipoArticulo = idTipoArticulo;
            proveedorDescripcion.Descripcion = descripcion;
            proveedorDescripcion.Estado = estado;
            return proveedorDescripcion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProveedor
        {
            get
            {
                return _IdProveedor;
            }
            set
            {
                if (_IdProveedor != value)
                {
                    OnIdProveedorChanging(value);
                    ReportPropertyChanging("IdProveedor");
                    _IdProveedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProveedor");
                    OnIdProveedorChanged();
                }
            }
        }
        private global::System.Int32 _IdProveedor;
        partial void OnIdProveedorChanging(global::System.Int32 value);
        partial void OnIdProveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPersona
        {
            get
            {
                return _IdPersona;
            }
            set
            {
                if (_IdPersona != value)
                {
                    OnIdPersonaChanging(value);
                    ReportPropertyChanging("IdPersona");
                    _IdPersona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPersona");
                    OnIdPersonaChanged();
                }
            }
        }
        private global::System.Int32 _IdPersona;
        partial void OnIdPersonaChanging(global::System.Int32 value);
        partial void OnIdPersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreRazonSocial
        {
            get
            {
                return _NombreRazonSocial;
            }
            set
            {
                if (_NombreRazonSocial != value)
                {
                    OnNombreRazonSocialChanging(value);
                    ReportPropertyChanging("NombreRazonSocial");
                    _NombreRazonSocial = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NombreRazonSocial");
                    OnNombreRazonSocialChanged();
                }
            }
        }
        private global::System.String _NombreRazonSocial;
        partial void OnNombreRazonSocialChanging(global::System.String value);
        partial void OnNombreRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                if (_IdEmpresa != value)
                {
                    OnIdEmpresaChanging(value);
                    ReportPropertyChanging("IdEmpresa");
                    _IdEmpresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEmpresa");
                    OnIdEmpresaChanged();
                }
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoArticulo
        {
            get
            {
                return _IdTipoArticulo;
            }
            set
            {
                if (_IdTipoArticulo != value)
                {
                    OnIdTipoArticuloChanging(value);
                    ReportPropertyChanging("IdTipoArticulo");
                    _IdTipoArticulo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoArticulo");
                    OnIdTipoArticuloChanged();
                }
            }
        }
        private global::System.Int32 _IdTipoArticulo;
        partial void OnIdTipoArticuloChanging(global::System.Int32 value);
        partial void OnIdTipoArticuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                if (_Descripcion != value)
                {
                    OnDescripcionChanging(value);
                    ReportPropertyChanging("Descripcion");
                    _Descripcion = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Descripcion");
                    OnDescripcionChanged();
                }
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                if (_Estado != value)
                {
                    OnEstadoChanging(value);
                    ReportPropertyChanging("Estado");
                    _Estado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Estado");
                    OnEstadoChanged();
                }
            }
        }
        private global::System.Int32 _Estado;
        partial void OnEstadoChanging(global::System.Int32 value);
        partial void OnEstadoChanged();

        #endregion

    
    }

    #endregion

    
}
