//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TECAv8Model", "FK__Empresa__IdEstad__0EA330E9", "Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(datos.Seguridad.Estado), "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(datos.Seguridad.Empresa), true)]

#endregion

namespace datos.Seguridad
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TECAv8Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TECAv8Entities object using the connection string found in the 'TECAv8Entities' section of the application configuration file.
        /// </summary>
        public TECAv8Entities() : base("name=TECAv8Entities", "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TECAv8Entities object.
        /// </summary>
        public TECAv8Entities(string connectionString) : base(connectionString, "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TECAv8Entities object.
        /// </summary>
        public TECAv8Entities(EntityConnection connection) : base(connection, "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Empresa> Empresa
        {
            get
            {
                if ((_Empresa == null))
                {
                    _Empresa = base.CreateObjectSet<Empresa>("Empresa");
                }
                return _Empresa;
            }
        }
        private ObjectSet<Empresa> _Empresa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Estado> Estado
        {
            get
            {
                if ((_Estado == null))
                {
                    _Estado = base.CreateObjectSet<Estado>("Estado");
                }
                return _Estado;
            }
        }
        private ObjectSet<Estado> _Estado;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Empresa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmpresa(Empresa empresa)
        {
            base.AddObject("Empresa", empresa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Estado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstado(Estado estado)
        {
            base.AddObject("Estado", estado);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TECAv8Model", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empresa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Empresa object.
        /// </summary>
        /// <param name="idEmpresa">Initial value of the IdEmpresa property.</param>
        /// <param name="razonSocial">Initial value of the RazonSocial property.</param>
        /// <param name="nombreComercial">Initial value of the NombreComercial property.</param>
        /// <param name="ruc">Initial value of the Ruc property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="idEstado">Initial value of the IdEstado property.</param>
        public static Empresa CreateEmpresa(global::System.Int32 idEmpresa, global::System.String razonSocial, global::System.String nombreComercial, global::System.String ruc, global::System.String direccion, global::System.Int32 idEstado)
        {
            Empresa empresa = new Empresa();
            empresa.IdEmpresa = idEmpresa;
            empresa.RazonSocial = razonSocial;
            empresa.NombreComercial = nombreComercial;
            empresa.Ruc = ruc;
            empresa.Direccion = direccion;
            empresa.IdEstado = idEstado;
            return empresa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                if (_IdEmpresa != value)
                {
                    OnIdEmpresaChanging(value);
                    ReportPropertyChanging("IdEmpresa");
                    _IdEmpresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEmpresa");
                    OnIdEmpresaChanged();
                }
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreComercial
        {
            get
            {
                return _NombreComercial;
            }
            set
            {
                OnNombreComercialChanging(value);
                ReportPropertyChanging("NombreComercial");
                _NombreComercial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreComercial");
                OnNombreComercialChanged();
            }
        }
        private global::System.String _NombreComercial;
        partial void OnNombreComercialChanging(global::System.String value);
        partial void OnNombreComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ruc
        {
            get
            {
                return _Ruc;
            }
            set
            {
                OnRucChanging(value);
                ReportPropertyChanging("Ruc");
                _Ruc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ruc");
                OnRucChanged();
            }
        }
        private global::System.String _Ruc;
        partial void OnRucChanging(global::System.String value);
        partial void OnRucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdImagen
        {
            get
            {
                return _IdImagen;
            }
            set
            {
                OnIdImagenChanging(value);
                ReportPropertyChanging("IdImagen");
                _IdImagen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdImagen");
                OnIdImagenChanged();
            }
        }
        private Nullable<global::System.Int32> _IdImagen;
        partial void OnIdImagenChanging(Nullable<global::System.Int32> value);
        partial void OnIdImagenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fondo
        {
            get
            {
                return _Fondo;
            }
            set
            {
                OnFondoChanging(value);
                ReportPropertyChanging("Fondo");
                _Fondo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fondo");
                OnFondoChanged();
            }
        }
        private global::System.String _Fondo;
        partial void OnFondoChanging(global::System.String value);
        partial void OnFondoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Logotipo
        {
            get
            {
                return StructuralObject.GetValidValue(_Logotipo);
            }
            set
            {
                OnLogotipoChanging(value);
                ReportPropertyChanging("Logotipo");
                _Logotipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logotipo");
                OnLogotipoChanged();
            }
        }
        private global::System.Byte[] _Logotipo;
        partial void OnLogotipoChanging(global::System.Byte[] value);
        partial void OnLogotipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicioSistema
        {
            get
            {
                return _FechaInicioSistema;
            }
            set
            {
                OnFechaInicioSistemaChanging(value);
                ReportPropertyChanging("FechaInicioSistema");
                _FechaInicioSistema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicioSistema");
                OnFechaInicioSistemaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicioSistema;
        partial void OnFechaInicioSistemaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioSistemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SitioWeb
        {
            get
            {
                return _SitioWeb;
            }
            set
            {
                OnSitioWebChanging(value);
                ReportPropertyChanging("SitioWeb");
                _SitioWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SitioWeb");
                OnSitioWebChanged();
            }
        }
        private global::System.String _SitioWeb;
        partial void OnSitioWebChanging(global::System.String value);
        partial void OnSitioWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TECAv8Model", "FK__Empresa__IdEstad__0EA330E9", "Estado")]
        public Estado Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Estado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estado> EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Estado", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TECAv8Model", Name="Estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Estado object.
        /// </summary>
        /// <param name="idEstado">Initial value of the IdEstado property.</param>
        public static Estado CreateEstado(global::System.Int32 idEstado)
        {
            Estado estado = new Estado();
            estado.IdEstado = idEstado;
            return estado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                if (_IdEstado != value)
                {
                    OnIdEstadoChanging(value);
                    ReportPropertyChanging("IdEstado");
                    _IdEstado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEstado");
                    OnIdEstadoChanged();
                }
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TECAv8Model", "FK__Empresa__IdEstad__0EA330E9", "Empresa")]
        public EntityCollection<Empresa> Empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empresa>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empresa>("TECAv8Model.FK__Empresa__IdEstad__0EA330E9", "Empresa", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
