//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("TECAv8Model", "FK__Empresa__IdEstad__0DAF0CB0", "Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(datos.Seguridad.Estado), "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(datos.Seguridad.Empresa), true)]

#endregion

namespace datos.Seguridad
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TECAv8Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TECAv8Entities usando la cadena de conexión encontrada en la sección 'TECAv8Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public TECAv8Entities() : base("name=TECAv8Entities", "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TECAv8Entities.
        /// </summary>
        public TECAv8Entities(string connectionString) : base(connectionString, "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TECAv8Entities.
        /// </summary>
        public TECAv8Entities(EntityConnection connection) : base(connection, "TECAv8Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Estado> Estado
        {
            get
            {
                if ((_Estado == null))
                {
                    _Estado = base.CreateObjectSet<Estado>("Estado");
                }
                return _Estado;
            }
        }
        private ObjectSet<Estado> _Estado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empresa> Empresa
        {
            get
            {
                if ((_Empresa == null))
                {
                    _Empresa = base.CreateObjectSet<Empresa>("Empresa");
                }
                return _Empresa;
            }
        }
        private ObjectSet<Empresa> _Empresa;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Estado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstado(Estado estado)
        {
            base.AddObject("Estado", estado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empresa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpresa(Empresa empresa)
        {
            base.AddObject("Empresa", empresa);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TECAv8Model", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empresa.
        /// </summary>
        /// <param name="idEmpresa">Valor inicial de la propiedad IdEmpresa.</param>
        /// <param name="razonSocial">Valor inicial de la propiedad RazonSocial.</param>
        /// <param name="nombreComercial">Valor inicial de la propiedad NombreComercial.</param>
        /// <param name="ruc">Valor inicial de la propiedad Ruc.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="idEstado">Valor inicial de la propiedad IdEstado.</param>
        public static Empresa CreateEmpresa(global::System.Int32 idEmpresa, global::System.String razonSocial, global::System.String nombreComercial, global::System.String ruc, global::System.String direccion, global::System.Int32 idEstado)
        {
            Empresa empresa = new Empresa();
            empresa.IdEmpresa = idEmpresa;
            empresa.RazonSocial = razonSocial;
            empresa.NombreComercial = nombreComercial;
            empresa.Ruc = ruc;
            empresa.Direccion = direccion;
            empresa.IdEstado = idEstado;
            return empresa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                if (_IdEmpresa != value)
                {
                    OnIdEmpresaChanging(value);
                    ReportPropertyChanging("IdEmpresa");
                    _IdEmpresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEmpresa");
                    OnIdEmpresaChanged();
                }
            }
        }
        private global::System.Int32 _IdEmpresa;
        partial void OnIdEmpresaChanging(global::System.Int32 value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreComercial
        {
            get
            {
                return _NombreComercial;
            }
            set
            {
                OnNombreComercialChanging(value);
                ReportPropertyChanging("NombreComercial");
                _NombreComercial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreComercial");
                OnNombreComercialChanged();
            }
        }
        private global::System.String _NombreComercial;
        partial void OnNombreComercialChanging(global::System.String value);
        partial void OnNombreComercialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ruc
        {
            get
            {
                return _Ruc;
            }
            set
            {
                OnRucChanging(value);
                ReportPropertyChanging("Ruc");
                _Ruc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ruc");
                OnRucChanged();
            }
        }
        private global::System.String _Ruc;
        partial void OnRucChanging(global::System.String value);
        partial void OnRucChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Logotipo
        {
            get
            {
                return StructuralObject.GetValidValue(_Logotipo);
            }
            set
            {
                OnLogotipoChanging(value);
                ReportPropertyChanging("Logotipo");
                _Logotipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logotipo");
                OnLogotipoChanged();
            }
        }
        private global::System.Byte[] _Logotipo;
        partial void OnLogotipoChanging(global::System.Byte[] value);
        partial void OnLogotipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicioSistema
        {
            get
            {
                return _FechaInicioSistema;
            }
            set
            {
                OnFechaInicioSistemaChanging(value);
                ReportPropertyChanging("FechaInicioSistema");
                _FechaInicioSistema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicioSistema");
                OnFechaInicioSistemaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicioSistema;
        partial void OnFechaInicioSistemaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioSistemaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SitioWeb
        {
            get
            {
                return _SitioWeb;
            }
            set
            {
                OnSitioWebChanging(value);
                ReportPropertyChanging("SitioWeb");
                _SitioWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SitioWeb");
                OnSitioWebChanged();
            }
        }
        private global::System.String _SitioWeb;
        partial void OnSitioWebChanging(global::System.String value);
        partial void OnSitioWebChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sector
        {
            get
            {
                return _Sector;
            }
            set
            {
                OnSectorChanging(value);
                ReportPropertyChanging("Sector");
                _Sector = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sector");
                OnSectorChanged();
            }
        }
        private global::System.String _Sector;
        partial void OnSectorChanging(global::System.String value);
        partial void OnSectorChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TECAv8Model", "FK__Empresa__IdEstad__0DAF0CB0", "Estado")]
        public Estado Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Estado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estado> EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estado>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Estado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TECAv8Model", Name="Estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Estado.
        /// </summary>
        /// <param name="idEstado">Valor inicial de la propiedad IdEstado.</param>
        public static Estado CreateEstado(global::System.Int32 idEstado)
        {
            Estado estado = new Estado();
            estado.IdEstado = idEstado;
            return estado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                if (_IdEstado != value)
                {
                    OnIdEstadoChanging(value);
                    ReportPropertyChanging("IdEstado");
                    _IdEstado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEstado");
                    OnIdEstadoChanged();
                }
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TECAv8Model", "FK__Empresa__IdEstad__0DAF0CB0", "Empresa")]
        public EntityCollection<Empresa> Empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empresa>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empresa>("TECAv8Model.FK__Empresa__IdEstad__0DAF0CB0", "Empresa", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
