//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace datos.Inventario
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InventarioEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InventarioEntities object using the connection string found in the 'InventarioEntities' section of the application configuration file.
        /// </summary>
        public InventarioEntities() : base("name=InventarioEntities", "InventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioEntities object.
        /// </summary>
        public InventarioEntities(string connectionString) : base(connectionString, "InventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioEntities object.
        /// </summary>
        public InventarioEntities(EntityConnection connection) : base(connection, "InventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grupo> Grupo
        {
            get
            {
                if ((_Grupo == null))
                {
                    _Grupo = base.CreateObjectSet<Grupo>("Grupo");
                }
                return _Grupo;
            }
        }
        private ObjectSet<Grupo> _Grupo;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grupo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrupo(Grupo grupo)
        {
            base.AddObject("Grupo", grupo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioModel", Name="Grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grupo object.
        /// </summary>
        /// <param name="idGrupo">Initial value of the IdGrupo property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Grupo CreateGrupo(global::System.Int32 idGrupo, global::System.String descripcion)
        {
            Grupo grupo = new Grupo();
            grupo.IdGrupo = idGrupo;
            grupo.Descripcion = descripcion;
            return grupo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEmpresa
        {
            get
            {
                return _IdEmpresa;
            }
            set
            {
                OnIdEmpresaChanging(value);
                ReportPropertyChanging("IdEmpresa");
                _IdEmpresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEmpresa");
                OnIdEmpresaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEmpresa;
        partial void OnIdEmpresaChanging(Nullable<global::System.Int32> value);
        partial void OnIdEmpresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGrupo
        {
            get
            {
                return _IdGrupo;
            }
            set
            {
                if (_IdGrupo != value)
                {
                    OnIdGrupoChanging(value);
                    ReportPropertyChanging("IdGrupo");
                    _IdGrupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdGrupo");
                    OnIdGrupoChanged();
                }
            }
        }
        private global::System.Int32 _IdGrupo;
        partial void OnIdGrupoChanging(global::System.Int32 value);
        partial void OnIdGrupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoArticulo
        {
            get
            {
                return _IdTipoArticulo;
            }
            set
            {
                OnIdTipoArticuloChanging(value);
                ReportPropertyChanging("IdTipoArticulo");
                _IdTipoArticulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoArticulo");
                OnIdTipoArticuloChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoArticulo;
        partial void OnIdTipoArticuloChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoArticuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEstado;
        partial void OnIdEstadoChanging(Nullable<global::System.Int32> value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _IdUsuario;
        partial void OnIdUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnIdUsuarioChanged();

        #endregion
    
    }

    #endregion
    
}
